org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.2
currentChangelog=- The default resource values for Step Crafter/Step Requester are now changeable in the client-side configuration screen

refinedarchitectVersion=1.7.0
refinedstorageVersion=3.2.1
refinedstorageQuartzArsenalVersion=2.0.6
jeiVersion=29.5.0.26
emiVersion=