org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.3
currentChangelog=- Fixed pressing Alt + Click not working inside Grid

refinedarchitectVersion=1.7.0
refinedstorageVersion=3.2.1
refinedstorageQuartzArsenalVersion=2.0.6
jeiVersion=29.5.0.26
emiVersion=