org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=1.21.1
modVersion=1.21.1-0.1.7
currentChangelog=- Improved Step Requester performance by adding a timeout on failed requested crafts

refinedarchitectVersion=1.4.1
refinedstorageVersion=2.0.4
refinedstorageQuartzArsenalVersion=1.0.7
jeiVersion=19.20.0.241
emiVersion=1.1.11+1.21